### ISSUE TITLE
Hyperlinks achter de sponsors 

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/Vrede-caravan-crowdfund#18]
Gelieve de Hyperlink achter de Logo`s van de sponsors te pompen zo dat men op het logo kan klikken.

https://www.vrede.be
https://www.akzonobel.com/nl/
http://www.garageteirlynck.be

**Comment by Tjoosten** [comment]
Closed due dumplicate Activisme-be/activisme.be#34
