### ISSUE TITLE
Aanpassen van titel en teksten

### ISSUE THREAD

**Issue by alfamongrel** [Activisme-be/Vrede-caravan-crowdfund#19]
1/ Gelieve de volledige titel te zetten voor wat we crowdfunden.

CROWDFUND :
bedeel_caravan

2/ foutje in Frans gedeelte 

Ik heb uw website bezocht om de juiste rekening te zoeken. Gezien ik Franstalig ben, viel me plotseling iets op. De vrede is la paix in het Frans. Le pet (op dezelfde manier uitgesproken) betekent "de scheet". La caravane du paix klinkt dus bijzonder grappig. Ik denk dat u la caravane de la paix bedoelde :-)

**Comment by Tjoosten** [comment]
transferred to Activisme-be/activisme.be
